name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          only-labels: "Status: Abandoned, Type: Question"
          stale-issue-label: stale
          stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 90 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 90 days with no activity.'
          days-before-stale: 14
          days-before-close: 90
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-pr-message: ''
          close-pr-message: ''